CREATE TABLE Strumento(
Cod  	VARCHAR,
Nome VARCHAR NOT NULL,
Watt FLOAT NOT NULL,
Ditta  VARCHAR NOT NULL,
Modello VARCHAR NOT NULL,
Costo FLOAT NOT NULL,
Annoaq INTEGER NOT NULL,
PRIMARY KEY(Cod)
);

CREATE TABLE Persona(
ID VARCHAR,
Nome VARCHAR NOT NULL,
Cognome VARCHAR NOT NULL,
DatAss DATE NOT NULL,
Psw VARCHAR NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE DivOsp(
Nome VARCHAR,
Rappr VARCHAR NOT NULL,
Ndip INTEGER NOT NULL,
Npl INTEGER NOT NULL,
Descrizione VARCHAR NOT NULL,
PRIMARY KEY(Nome),
FOREIGN KEY(Rappr) REFERENCES Persona(ID)
);

CREATE TABLE InCarico(
CodS VARCHAR,
NomeD  VARCHAR,
PRIMARY KEY(Cod, Nome),
FOREIGN KEY(Cod, Nome) REFERENCES Strumento(Cod), DivOsp(Nome)
);

CREATE TABLE Manutenzione(
CodS VARCHAR,
Data DATE NOT NULL,
Durata VARCHAR NOT NULL,
NumOp INTEGER UNSIGNED NOT NULL,
IDitta VARCHAR NOT NULL,
Urgenza VARCHAR NULL,
Costo FLOAT NULL,
PRIMARY KEY(CodS, Data),
FOREIGN KEY(CodS) REFERENCES Strumento(Cod)
);

CREATE TABLE UtStr(
DataIn DATE,
DataF DATE,
Motivo VARCHAR NOT NULL,
Resp VARCHAR NOT NULL,
CodS VARCHAR NOT NULL,
NomeD VARCHAR NOT NULL,
PRIMARY KEY(DataIn, DataF, CodS),
FOREIGN KEY(Resp, CodS, NomeD) REFERENCES Persona(ID), Strumento(Cod), DivOsp(Nome) 
);

